---
version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: monthly
  - directory: /
    groups:
      docs:
        patterns:
          - "*"
    package-ecosystem: pip
    schedule:
      interval: monthly
