---
site_name: Designing the Dungeon
site_description: A Digital Garden for Dungeons and Dragons
site_author: Tyler Titsworth
site_url: https://tylertitsworth.github.io/designing-the-dungeon/
nav:
  - Introduction: index.md
  - Projects: projects.md
plugins:
  - autolinks
  - search
  - exclude-search:
      exclude: [newsletter/*]
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  font:
    text: Cabin
    code: Ubuntu
  logo: assets/bwlogo.png
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep purple
      accent: grey
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep purple
      accent: blue grey
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tylertitsworth
    - icon: fontawesome/solid/rss
      link: https://tylertitsworth.github.io/designing-the-dungeon/newsletter/0_newsletter_index
repo_name: tylertitsworth/designing-the-dungeon
repo_url: https://github.com/tylertitsworth/designing-the-dungeon
