---
name: Docs
on:
  pull_request: null
  push:
    branches:
      - main
concurrency:
  group: build-gh-pages
  cancel-in-progress: true
permissions: read-all
jobs:
  mkdocs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8
          cache: pip
      - name: Install python requirements
        run: python -m pip install -r requirements.txt
      - name: Build
        run: mkdocs build --clean
      - name: Commit files
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/newsletter
          git diff-index --quiet HEAD \
            || git commit -m "chore: publish newsletters"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: site
      - uses: actions/deploy-pages@v4.0.5
        if: ${{ github.event_name == 'push' }}
