---
name: Docs
on:
  pull_request: null
  push:
    branches:
      - main
permissions: read-all
jobs:
  mkdocs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.8
          cache: pip
      - name: Install python requirements
        run: python -m pip install -r requirements.txt
      - name: Build
        run: mkdocs build --clean
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: site
      - uses: actions/deploy-pages@v4.0.5
        if: ${{ github.event_name == 'push' }}
